version: '3'

services:
  web:
    env_file:
      - '.env.docker.local'
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres:postgres.local

  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
       - database:/var/lib/postgresql/data

volumes:
  database:
